-- 코드를 입력하세요
SELECT USER_ID, PRODUCT_ID FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID, PRODUCT_ID DESC;
-- 서브쿼리, GROUPING(하나만 나오는 문제점)
-- 15, 15, 12과 48, 15 12가 겹침